### ISSUE TITLE
LDpred2: Using precomputed ld and correlation matrix

### ISSUE THREAD

**Issue by deepchocolate** [comorment/containers#108]
**Is your feature request related to a problem? Please describe.**
So far I've tested the LDpred2.R script on real data using the infinitessimal mode, which seemed to work, but the auto mode did not as there was some problem with infinite values in the correlation matrix. To investigate such errors when these are not replicable using test data becomes challenging due to that calculation of the matrix takes several errors. Therfore the calculation of this matrix should be separated from the `ldpred2.R` script. This would
- Make debugging easier
- Simplify usage (less flags to keep track of for the current step)
- Improve speed as the matrix can be resused when running different modes of LDpred2. There is the issue of which SNPs to use when calculating the correlation matrix when using different sumstats, but that can be addressed later.

**Describe the solution you'd like**
All functionality that relates to calculating the correlation matrix is moved to a script of its own. The process would instead look like:
1) `createBackingFile.R file.bed file.rds`
2) `calculateSnpCorrelation.R file.rds snpcorr.rds`
3) `ldpred2.R file.rds snpcorr.rds sumtats.txt output.txt`

[This R-script](https://github.com/privefl/paper-infer/blob/main/code/example-with-provided-LD.R) provides an example how to use the ld provided by the creators of LDpred. This approach can be implemented in (2). If appropriate those ld files (from the [creators tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html)) could maybe be provided in this repository as well. I guess there are cases when you can't run step 2.

**Additional context**
I've seen some issues on the LDpred2 github of people having similar ideas to speed up calculation of PGS using different sumstats. The challinge is that the format of the matrix used to calculate the correlation seem challening to handle. Appears you would have to create a matrix in the FBM format for all the SNPs you need and then subset this matrix and convert to SFBM for each set of SNPs for a particular sumstat file. But I don't know how big deal it is for normal usage if the overlap varies.

**Comment by espenhgn** [comment]
Thanks @deepchocolate, 
@ofrei and I discussed a similar issue yesterday. Sounded like he wanted to also split these calculations in separate steps, so can the two of you coordinate in order to not duplicate work?

**Comment by deepchocolate** [comment]
> Thanks @deepchocolate, @ofrei and I discussed a similar issue yesterday. Sounded like he wanted to also split these calculations in separate steps, so can the two of you coordinate in order to not duplicate work?
Sounds good!

**Comment by deepchocolate** [comment]
> @deepchocolate good plan! Could you start with `calculateSnpCorrelation.R`? This part I haven't worked on at all. However I'm almost done with updated version of `ldpred2.R` which relies on getting pre-computed LD matrix as input. For now I took out from `ldpred2.R` the code hat computes LD matrix, and instead used the code that loads `/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr` matrix. I'll send PR with updated version in an hour or so

Great! I have started on that part...

**Comment by deepchocolate** [comment]
@espenhgn @ofrei I repeated the analyses in MoBa yesterday using the auto-mode of LDpred and the error was gone :)
