### ISSUE TITLE
Test for king fails in multi-user systems

### ISSUE THREAD

**Issue by ttfiliz** [comorment/containers#135]
**Describe the bug**
King test in `test_gwas.py` fails if output files are owned by another user.

**To Reproduce**
Run `py.test tests/test_gwas.py -k test_gwas_king` while the `/tmp/king.kin`, `/tmp/king.kin0` and `/tmp/kingallsegs.txt` files  are owned by another user.

**Expected behavior**
The test should pass

**Setup (please complete the following information - if applicable):**
 - OS: Ubuntu 21.04 (5.11.0-49-generic)
 - Docker version: 20.10.7
 - Singularity version: 3.7.4
 - Container file and version: gwas.sif

**Comment by espenhgn** [comment]
Perhaps try and create a temp dir using the Python [tempfile](https://docs.python.org/3/library/tempfile.html#module-tempfile) module's `tempfile.gettempdir()` function for these tests?
