### ISSUE TITLE
LDpred2: Support sumstats files w. character encoding for chromosome

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#151]
**Describe the bug**
Some sumstats files may use `X` and similar encoding for some chromosomes. This now results in a crash:

```
### Reading summary statistics Height.gwas.Xchrom.txt.gz 
Loaded 529504 SNPs
Removing rows with non-integers in column CHR 
Removing 0 SNPs...
Retained 520938 SNPs
Converting odds-ratio to log scale
Filtering SNPs based on --chr2use
Retained 520938 out of 520938 
Matching sumstats to genotypes
520,938 variants to be matched.
Error in `vctrs::vec_in()`:
! Can't combine `chr` <character> and `chr` <integer>.
Backtrace:
     ▆
  1. ├─bigsnpr::snp_match(...)
  2. │ ├─...[]
  3. │ ├─base::`[.data.frame`(...)
  4. │ └─vctrs::vec_in(sumstats[, join_by[1:2]], info_snp[, join_by[1:2]])
  5. └─vctrs (local) `<fn>`()
  6.   └─vctrs::vec_default_ptype2(...)
  7.     ├─base::withRestarts(...)
  8.     │ └─base (local) withOneRestart(expr, restarts[[1L]])
  9.     │   └─base (local) doWithOneRestart(return(expr), restart)
 10.     └─vctrs::stop_incompatible_type(...)
 11.       └─vctrs:::stop_incompatible(...)
 12.         └─vctrs:::stop_vctrs(...)
 13.           └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
Execution halted
```
This was the result of replacing chr. 22 by `X` in the sumstats file.
@ofrei, @deepchocolate, is this something we should support? I lean in the "not" direction as it's easy enough to rewrite the sumstats file.

**Comment by deepchocolate** [comment]
@espenhgn Characters are supposed to be filtered out, so it seems that this isn't working properly:
https://github.com/comorment/containers/blob/ff12bb001cc35928fa698a59c768f697d6fc337e/usecases/LDpred2/ldpred2.R#L127-L134

**Comment by espenhgn** [comment]
Ok, so bug label then. @johnshorter encountered this issue with his sumstats file.

**Comment by deepchocolate** [comment]
> Ok, so bug label then. @johnshorter encountered this issue with his sumstats file.

Siim aswell. I can add a fix in my existing pull request. I think it's just to use `getNumericIndices()` instead of `is.charachte()` in the condition.
