### ISSUE TITLE
Improvements in folder structure

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#152]
**Is your feature request related to a problem? Please describe.**

Currently we have src/ folder very well organized with all Docker files, but scripts that build on top of containers (e.g. gwas/gwas.py  and usercases/LDpred2/LDpred2.R) are scattered across the folder tree. I suggest to consolidate them in one location as this will make it easier documenting those scripts.

**Describe the solution you'd like**

rename src -> docker
create pipelines folder (any better name?) containing gwas.py & config.yaml, LDpred2.R and related scripts that we currently have under usecases, PRS pipeline in python
move gwas/pheno_geno_specification.md and sumstats_specification.md into an existing docs folder (also split pheno_geno_spec into two files)
adjust "usecases" to use stuff from pipelines, but not the other way around

**Comment by espenhgn** [comment]
I'm implementing this, but making some minor adjustments to the suggested layout:
```
.
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── citation.cff
├── docker
│   ├── Makefile
│   ├── README.md
│   ├── dockerfiles
│   ├── scripts
│   └── software
├── docs
│   ├── README.md
│   ├── singularity
│   └── specifications
├── pytest.ini
├── reference
│   ├── README.md
│   ├── examples
│   ├── hapgen
│   ├── hapmap3
│   ├── hrc
│   └── sumstats
├── scripts
│   ├── README.md
│   ├── gwas
│   └── pgs
├── singularity
│   ├── *.sif
├── sphinx-docs
│   └── source
├── tests
│   ├── extras
│   ├── test_LDpred2
│   ├── test_*.py
├── usecases
│   ├── README.md
│   ├── bolt-lmm_demo.md
│   ├── bolt_out
│   ├── gwas_demo
│   ├── ...
└── version
    └── version.py
```
 Got to walk the Markdown files, etc., and check that the docs build and other cross-references are not broken.
