### ISSUE TITLE
`LDpred2/complementSumstats.R`: rename `#CHROM` column in output

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#157]
**Is your feature request related to a problem? Please describe.**
The name for this column in the reference file contains a number sign (#) which may be a nuisance in downstream code/analyses.
I see no reason to write this special character in the output. 

**Describe the solution you'd like**
Column headers in the output should not contain special characters. 
@deepchocolate, shall we decide on a common name, like `CHR`? It's what we have in our cleansumstats repository. 

Edit: Would also update the script/README files to suggest writing `--output-file` directly. Piping to gzip will include warnings etc. in the written file which is certainly not wanted.

**Comment by deepchocolate** [comment]
I agree on the column name `CHR``. It might be a bit outside the scope of `complementSumstats.R` to deal with column names, but I don't have a strong opionion on it. How would it be implemented? The number of columns can vary both in the sumstats and the reference, so would it be just the chromosome column, eg an argument with a default like `--col-out-chr CHR`?

Agree with the README update!

**Comment by espenhgn** [comment]
I can make a patch using the dplyr package, renaming columns as:
```
df <- df %>% dplyr::rename("#CHROM" = "CHR")
```
using the input arguments.
