### ISSUE TITLE
Document steps needed to make a new release of this repository

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#168]
A few steps that I'm aware:
* bump the version in [version/version.py](version/version.py) file
* update [CHANGELOG.md](CHANGELOG.md)
* make sure all ``.sif`` containeres that were changed are built and checked-in to [singularity](singularity)
* sync latest version to TSD p697 project
* create new tag (or an alternative procedure?)

**Comment by espenhgn** [comment]
I'll add this info. By heart, making releases quite straightforward and could be further automatized, but we can make things more stringent (if we want). If we stick to the [semantic versioning scheme](https://semver.org), there are some good pointers.
- stick with the `<MAJOR>.<MINOR>.<PATCH>` scheme with possible extensions. 
- require updates to CHANGELOG.md
- every PR should bump the version tag depending on the nature of the change (minor fix means bumping `<PATCH>` and so forth)
- create a tag for each change in version (excluding `dev`,`rc#` extensions, and similar). We can set up an automated action for this: https://github.com/marketplace/actions/auto-tag (may need to convert to `version/version.py` to `package.json` for this one).
- each new tag warrants a new release. There are also actions for doing this, e.g., https://github.com/marketplace/actions/automatic-releases.
- new releases should trigger Zenodo.org code deposit automatically
- readthedocs.org should do docs builds automatically with each merged PR.
