### ISSUE TITLE
Document syncing to TSD/p697 in RELEASES.md

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#174]
** The documentation issue** 
Documentation on how to sync this project onto TSD/p697 is missing (cf. https://github.com/comorment/containers/issues/168) in [RELEASES.md](https://github.com/comorment/containers/blob/main/RELEASES.md)

**Comment by ofrei** [comment]
I have cloned github.com/comorment/containers repo on NREC. To update it on TSD I do this:
```
cd /nrec/space/ofrei/github/comorment/containers
git pull
tsd-s3cmd sync  --delete-removed /nrec/space/ofrei/github/comorment/containers s3://github/comorment/
```

This command may take long time, and it's quite silent. I've used ``--verbose  --exclude=".git/*" --no-check-md5`` flags to speed it up and make verbose. Also it's dangerous with --delete-removed flag, as if source or target location is misspecified there will be a lot of unexpected deletes. E.g. the trailing slash (``/`` in ``s3://github/comorment/``) is really important.

This uses https://github.com/unioslo/tsd-s3cmd tool to sync data in and out TSD.  The ``s3://github`` bucket was created from my user and I don't know if other users can write to this bucket - I've previously had issues with this. However other users were able to make changes to some of my other buckets on TSD, so if there are "write" access issues this should be solvable.

By default tsd-s3cmd asks for password and OTP tocket. However it's possible to setup tsd-s3cmd   with a token that lasts for 1 month, see ``tsd-s3cmd --print-token-for put``. With this tocket stored in ~/.s3token_p697 the command may look like this:
```
/nrec/projects/ofrei/miniconda3/bin/s3cmd sync --add-header=token:$(cat ~/.s3token_p697) --add-header=x-project-select:p697 /nrec/space/ofrei/github/comorment/containers s3://github/comorment/
```
