### ISSUE TITLE
`LDpred2`: Remove time thief

### ISSUE THREAD

**Issue by deepchocolate** [comorment/containers#181]
**Is your feature request related to a problem? Please describe.**
I was puzzled by that it took so much time to load the genotype data, and it turns out that it's these lines that seeem to be the culprit: 
https://github.com/comorment/containers/blob/a195c980c3636faad4de4ee8543d7d636cf16bb4/scripts/pgs/LDpred2/ldpred2.R#L139-L140
I've tested commenting these lines out and the time it takes generating PGS for 3 sumstats is down with at least 60%.

**Describe the solution you'd like**
I suggest reming the above lines. What will happen is just that an error will instead appear during the scoring in `snp_ldpred2_inf` or `snp_ldpred2_auto` (something like "you can't have missing values in X"). That's error is maybe not so informative, but it might be possible to capture that error and give more details ("impute data or pass --geno-impute-zero").

**Comment by espenhgn** [comment]
Sounds fine. More familiar with Python style [Exceptions](https://docs.python.org/3/tutorial/errors.html#), but I'm sure there are equivalent functionality in R.
