### ISSUE TITLE
LDpred2.R: if `--merge-by-rsid` option is used, ignore `--col-bp` arg

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#191]
@johnshorter encountered an issue that if the `--merge-by-rsid` option is used, the `bp`  column required by the script is not used, except for some then-redundant checks:
https://github.com/comorment/containers/blob/a343a17e864fcb37c5fe13611089f2c5a3ebc47a/scripts/pgs/LDpred2/ldpred2.R#L148C8-L148C8are

This could be handled neater, making `--col-bp` optional if `--merge-by-rsid` is used.

**Comment by deepchocolate** [comment]
Column `chr` is still needed, right?
https://github.com/comorment/containers/blob/a343a17e864fcb37c5fe13611089f2c5a3ebc47a/scripts/pgs/LDpred2/ldpred2.R#L228
`snp_match` requires `chr`, `a0`, `a1`, and `rsid` or `pos`
https://privefl.github.io/bigsnpr/reference/snp_match.html

**Comment by johnshorter** [comment]
Yes CHR is needed as it breaks the ld blocks down by each chromosome.


John
