### ISSUE TITLE
Collect feedback and include additional packages into R container

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#197]
**Is your feature request related to a problem? Please describe.**
Currently there are some fairly common R packages that are not included in the R container, e.g. [glmer](https://www.rdocumentation.org/packages/lme4/versions/1.1-34/topics/glmer). It would be great to collect feedback from biostats users about what R packages they may encounter, and include them in the R container.

I've noticed that on TSD R modules are built with foss, while Python modules are built with GCC. I haven't found a way of loading both in the same session. In some cases it's handy to call R from python, and for that it would be great to have more modules available in R container.

**Comment by espenhgn** [comment]
Will incorporate via #196.
