### ISSUE TITLE
Add additional phasign and impute software

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#198]
**Is your feature request related to a problem? Please describe.**
It would be great to add more software that is often use for phasing, imputation :

* beagle - GPL v3 - http://faculty.washington.edu/browning/beagle/beagle.html
* eagle - GPL v3 - https://alkesgroup.broadinstitute.org/Eagle/
* shapeit5 - MIT ;  this already has its own Docker; https://odelaneau.github.io/shapeit5/
* switchError - MIT ( https://github.com/ofrei/switcherror fork of https://github.com/SPG-group/switchError )

Here is a list of what's already available :
```
install_qctools
install_king
install_vcftools
install_htslib
install_bcftools
install_minimac4
install_bgenix
install_shapeit4
```

Shapeit2 and impute2 / impute4 - sadly can't be included; most likely same for [impute5](https://jmarchini.org/software/#impute-5) and [duohmm](https://mathgen.stats.ox.ac.uk/genetics_software/duohmm/duohmm.html)

**Comment by espenhgn** [comment]
duohmm carries an [MIT license](https://github.com/jaredo/duohmm/blob/master/LICENSE), so can be included.
