### ISSUE TITLE
Avoid requirement that FID and IID are the same in gwas.py

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#21]
Current scripts are developed under assumption that FID and IID are the same, and only IID is used to identify individuals and link them between .pheno file and the genetic files. Good to design this in a way that is more flexible.

**Comment by ofrei** [comment]
This is less straighforward than I expected, because ``VCF and .bgen files contain single-part sample IDs`` (see here: https://www.cog-genomics.org/plink/2.0/input#sample_id_convert ). I think we can allow FID that is different from IID (both in .pheno file and in .fam files), but we should simply ignore such FID, and only use IID to match individual's genotypes and phenotypes. We should also ignore FID when we call PLINK.  Let's discuss this design.

**Comment by johnshorter** [comment]
I had experienced this issue when using regenie and saige. 

A temporary solution I found was to force PID and IID to be identical, in both the phenotype file and the genotype (.fam) file. This was critical for the first step (job 1) where the relationship matrix was built using genotype files with limited markers.
It seems like the .VCF files we use in iPSYCH do not have an issue during the second step (job 2).

**Comment by ofrei** [comment]
I'm still thinking how to best implement this. Btw, there is another related issue - current format for the phenotype file expects a column named IID, and it's not possible to customize this. For example in MoBa's master spreadsheet we have a column  named SENTRIXID, and it is expected to match plink's IID column from FAM file. It would be good to have an option to specify a custom column name. Or this can be taken from the dictionary file - a column with TYPE equal to IID can be used as identifier. I'll think how best to implement this.

**Comment by ofrei** [comment]
@ttfiliz try to have a copy of ``example_3chr.fam`` file where FID column is replaced with something other than corresponding values of the IID column. It can be either all FID set to 0, or e.g. ``FID=int(line_number / 2)``. Then use this as input to unit gwas_test_py.py and see if it still works.

**Comment by ofrei** [comment]
Also test it for both plink and regenie.

**Comment by ofrei** [comment]
This one is by design - not a big limitation for users to ensure that .fam file has unique IID column (and it also matches IID in .pheno file)
```
def read_fam(args, fam_file):
...
    if np.any(fam['IID'].duplicated()): raise(ValueError("IID column has duplicated values in --fam file"))
...
```

**Comment by ofrei** [comment]
On a slighly separate topic, we've implement a support for a custom name of the  IID column in .pheno file (https://github.com/comorment/containers/commit/2fa7c95301a4fc32d824b683e1a2902f9925f775). 
When it comes to FID column, it seem to work just fine if FID is different from IID, so we couldn't reproduce the issue mentioned in the title.
@ttfiliz please submit your adjusted example_3chr.fam where FID column has ``2`` (or whatever value it has). Also make a copy of the corresponding .bed and .bim files (because for --geno-file we need all of the files to have the same prefix). And make new tests similar to those we have now in ``test_gwas_py.py`` that pass adjusted ``--geno-file example_3chr_adjusted.fam``. If this works then we don't need to test .vcf, .pgen and .bgen formats.

**Comment by ofrei** [comment]
@ttfiliz also while we are on this topic could you please test that if .dict file defines ``SENTRIXID`` column of type ``IID``, and ``.pheno`` file has ``SENTRIXID`` column that match the second column of the .fam file, then everything still works. No need for unit test, just check manually that this works
