### ISSUE TITLE
Consider adding SNPTEST 2.5.6 to gwas.sif container

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#211]
**Is your feature request related to a problem? Please describe.**
It would be nice to have SNPTEST software in a container
However it's not clear what license it has - the link to the license is broken
https://www.well.ox.ac.uk/~gav/snptest/#download - here the link to the license is broken

@ttfiliz could you ask SNPTEST mail list about the license?

**Comment by espenhgn** [comment]
I think we can expect the same limiting license as for other Oxford University, e.g., https://www.dropbox.com/sh/mwnceyhir8yze2j/AADbzP6QuAFPrj0Z9_I1RSmla?dl=0&preview=LICENCE.txt (from Impute5)
