### ISSUE TITLE
Update QCTOOL to 2.2.0

### ISSUE THREAD

**Issue by ttfiliz** [comorment/containers#212]
**Is your feature request related to a problem? Please describe.**
The current version of QCTOOL is not able to compute info scores for X-chromosome. 

**Describe the solution you'd like**
Update QCTOOL to 2.2.0

**Comment by espenhgn** [comment]
Encountered some issues compiling v2.2.0, but v2.2.2 and related binaries compiled from source are included in PR #214.

**Comment by ttfiliz** [comment]
Tahnk you @espenhgn, this should work as well.
