### ISSUE TITLE
`gwas.sif`: Include samtools, bedtools, liftOver; upgrade others

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#219]
**Is your feature request related to a problem? Please describe.**
samtools ( http://www.htslib.org/download/ ) package is developed by the same people as bcftools and htslib which we already have. It's useful (.e.g it include TABIX feature to index files, as required by some other packages - e.g. lokuszoom). Great if possible to include samtools  in gwas.sif

**Comment by espenhgn** [comment]
Adding samtools together with bedtools (MIT license), liftOver (no-license - free for non-commercial use).
