### ISSUE TITLE
A small bug : na.rm is missing : quantile (na.rm = T, ...)

### ISSUE THREAD

**Issue by erskck-zi** [comorment/containers#227]
https://github.com/comorment/containers/blob/c5770959620ac7a658d640ade3b1384041fdc803/scripts/pgs/LDpred2/ldpred2.R#L314

**Comment by espenhgn** [comment]
Thanks for the notification. 
@deepchocolate, do you agree with parsing `na.rm=T` in this call to [quantile](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile)? The default is otherwise "`na.rm=F`". 

Perhaps fix this via PR #178.

**Comment by erskck-zi** [comment]
Thanks for implementing these scripts! Yes, in the tutorial they used na.rm=T.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by espenhgn** [comment]
> Thanks for implementing these scripts! Yes, in the tutorial they used na.rm=T. 

Fine, then we should as well.
