### ISSUE TITLE
singularity/saige.sif is a textfile, instead of the actual singularity image

### ISSUE THREAD

**Issue by rzetterberg** [comorment/containers#28]
Before commit c38f807da7e452b478d79fe0895a6feb0471a43b the [file `singularity/saige.sif` was **702 MB**](https://github.com/comorment/containers/blob/a251e574151d3ade00123496dcb30e88705c65eb/singularity/saige.sif) in size, after the commit [that file is **295 Bytes**](https://github.com/comorment/containers/blob/c38f807da7e452b478d79fe0895a6feb0471a43b/singularity/saige.sif). 

This is the content of that file now:

```
version https://git-lfs.github.com/spec/v1
<<<<<<< HEAD
oid sha256:8c870154d08604b5eefe2a4635a6ef22c2cf69b4dccb72f12367bda467dffb43
size 736071680
=======
oid sha256:1d8e3762db280395a73eb9bd3a070f6666717f8d0dbc76cb7738e256bf5649da
size 899510272
>>>>>>> 205045b7ae8864036476cf68d358bd0e9ce045c0
```

It seems like the file has been accidentally commited as a literal LFS textfile, instead of the actual singularity image.

**Comment by bayramakdeniz** [comment]
Thanks for letting me know. I have pushed the actual container now
