### ISSUE TITLE
Several errors with Saige (empty GMMATmodelFile)

### ISSUE THREAD

**Issue by johnshorter** [comorment/containers#29]
Hello, 

The new version of Saige is running, but I have encountered (and fixed) some errors, but I have hit a new issue. 

First, I have several long flag errors, and they were solved by removing the following flags:
 --long flag "numLinesOutput" is invalid
 --long flag "IsOutputAFinCaseCtrl" is invalid
 --long flag "IsOutputNinCaseCtrl" is invalid
 
 The issue below in the screen shot is more complicated, I do not know how to change the GMMATmodelFile, but it appears empty and causes an error that halts Saige. Interestingly, this wasn't an error before the last update. 
 
![image](https://user-images.githubusercontent.com/19779071/161512388-f8f7702a-7248-44c9-80ea-d47bd2d123d2.png)

**Comment by ofrei** [comment]
@johnshorter Hi John. Thanks  - I'll work closely with @bayramakdeniz  to investigate and fix ASAP.

**Comment by ofrei** [comment]
@johnshorter let's presume SAIGE 1.0 isn't ready yet, and go back to SAIGE 0.44 while we're waiting for 1.0 to became more stable. I put further comments here https://github.com/comorment/containers/issues/27
