### ISSUE TITLE
`--config` is not passed on to slurm jobs that run `mege-regenie`, `merge-saige` or `merge-plink2` 

### ISSUE THREAD

**Issue by rzetterberg** [comorment/containers#34]
Here's the expected the behavior:

```feature
Given I have an arguments file named "my_test.args" in the current directory
  And my arguments file have the argument "--analysis regenie figures"
  And my arguments file have the argument "--out my_test"
  And I have an config file named "my_test.yaml" in the current directory
 When I run "gwas.py --argsfile my_test.args --config my_test.yaml"
 Then the file "my_test.3.job" is created
  And the file "my_test.3.job" contains the command "gwas merge-regenie" 
  And the file "my_test.3.job" contains the argument "--config my_test.yaml"
```

But currently when going through this scenario (tested with 5d3a5b496fdaa9a05f839eb83613c3d60cf9b55a) the last step fails, the argument `--config` is absent from the job file.

**Comment by ofrei** [comment]
@rzetterberg actually there is more to this, I've pushed two more commits with commit message describing this in more detail.

https://github.com/comorment/containers/commit/d96347cde627f4b035b76e0d7c63af719c9ea3aa

https://github.com/comorment/containers/commit/c720a82e7463c11f8109693c6e1eb8ff5db09530

**Comment by rzetterberg** [comment]
Perfect, not supplying something that isn't used is a much better approach 👍🏻
