### ISSUE TITLE
Include Dockerfile and scripts into comorment/containers repo

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#39]
Currently we use https://github.com/comorment/gwas to keep all *development*-related scripts for comorment containers.
The https://github.com/comorment/containers repo is used to release singularity containers (as .sif files), to keep reference data, and for user documentation. This separation is suboptimal, and it makes more sense to include all development-related scripts (Dockerfile, bash scripts, some dev instuctions, etc) in https://github.com/comorment/containers. However we should keep those codes somewhat hidden from the end user, for example move them to a new ``source`` folder in the root of this repo. After than the github.com/comorment/gwas repo can be archived (e.g. kept in case we need code history, but we lock is so no futher changes can be submitted).

Also, we should change our development model and start using feature & bug-fix branches, using a pull request and code review to integrate changes into the main branch.

**Comment by espenhgn** [comment]
Figured we can add a task list of what we will include:
- [ ] hello.sif
- [ ] gwas.sif
- [ ] python3.sif
- [ ] r.sif 
- [ ] saige.sif 
- [ ] enigma-cnv.sif 
- [ ] matlabruntime.sif

Omitted ldsc.sif; mixer, ldsc, magma, pleiofdr should also not be included here for reasons listed in #40.
