### ISSUE TITLE
ERROR: No setuid installation found, p33 , tsd

### ISSUE THREAD

**Issue by zillurbmb51** [comorment/containers#5]
Hi, I was trying to run ldsc.py in p33 in tsd but getting the above mentioned error. Any help?
![ldsc-container-p33-error](https://user-images.githubusercontent.com/12833907/123303745-6bd83a00-d51e-11eb-8f1c-0ad1e826d04a.png)

**Comment by ofrei** [comment]
Most likely this has something to do with which ``singularity`` executable you're using.
You need to work on the app node. Also, it's important to ``module purge`` so you're not loading a singularity module - we need to use locally installed singularity.
If still doesn't work try ``which singularity`` and ``singularity --version`` and paste here the result.

**Comment by zillurbmb51** [comment]
Thanks. Here it is:
![singularity-p33](https://user-images.githubusercontent.com/12833907/123306916-261d7080-d522-11eb-8b20-d935fc10cef1.png)

**Comment by zillurbmb51** [comment]
After unloading singularity module, I am getting this:
![after-unloading-singularity](https://user-images.githubusercontent.com/12833907/123307342-ad6ae400-d522-11eb-803e-ca35651ae142.png)

**Comment by ofrei** [comment]
Good, it seem ``module purge`` solved the first problem.
To the ``no such file or directory``, this is probably due to the way folders are mounted to the container. Please take a look here:
https://github.com/comorment/containers/blob/main/docs/hello.md#mapping-your-data-to-singularity-containers
and also  here:
https://sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html
If this doesn't help to solve the problem please let me know!

**Comment by zillurbmb51** [comment]
Thanks. I just needed to copy the input to the working directory. However, getting another error, 
![value-error-zscore](https://user-images.githubusercontent.com/12833907/123311520-8fec4900-d527-11eb-9d06-486bc2ad429d.png)

**Comment by ofrei** [comment]
This is a bad luck - the message about Z-score is a real problem with the data.
Where the input sumstats file is coming from?
Is it possible to re-calculate z-score from p-value and effect direction column as e.g. in "sumstats.py zscore" ?

**Comment by zillurbmb51** [comment]
Thanks. I would try that. However, Now, I copied 10 sumstats from */groups/biostat/SUMSTATv2/ldsr folder and all of them showing the attached error:
![value-error-again-ldsr-sumstats](https://user-images.githubusercontent.com/12833907/123314312-ba8bd100-d52a-11eb-8cab-cdc0cdb97d63.png)

**Comment by ofrei** [comment]
SUMSTATv2/ldsr is after munge_sumstats,i.e. can be directly used with
ldsc.py h2 and ldsc.py rg.
If  you need before munge_sumstats, take the file from SUMSTATv2/nomhc

**Comment by zillurbmb51** [comment]
Thank you. Yes, ldsc.py --rg is running with those sumstats. Only one sumstats, `CARDIOGRAM_CAD_2017_UKB.sumstats.gz` is not present in SUMSTATSv2/ldsr folder. When I was trying to use munge_sumstats.py, I was getting the `ValueError: Warning median value of Z is 0.69`. I also tried using `sumstats.py zscore` but same error.

**Comment by ofrei** [comment]
``CARDIOGRAM_CAD_2017_UKB`` ldsr file is missing for a reason - most likely there is no effect direction info in the summary stats. Perhaps there is another CAD?

**Comment by zillurbmb51** [comment]
Ohh. Yes, `CARDIOGRAM_CAD_2015_UKB` is available, I was using this. One thing, I am getting rg of all phenotypes vs the 1st one (attached). How get I get all vs all, To create a heatmap,
![rg-pheno1-vs-all](https://user-images.githubusercontent.com/12833907/123322104-258dd580-d534-11eb-9c33-c48591edae43.png)
 I mean, pheno1 vs pheno2, pheno1 vs pheno3, pheno2 vs pheno3.

**Comment by ofrei** [comment]
For that one need to run "ldsr.py rg" once for every trait.

**Comment by ofrei** [comment]
Seem to be resolved
