### ISSUE TITLE
Intermittent failure in scripts/from_docker_image.sh

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#52]
Sometimes when I use ``scripts/from_docker_image.sh`` script it fails with an error. Here is how I call the script:

```
>sudo make gwas.sif
```
which in turn triggers the following command
```
docker build -t gwas -f containers/gwas/Dockerfile . && scripts/convert_docker_image_to_singularity.sh gwas          
```
The first part of it succeeds, but the second fails:
```
...
Successfully built 6038cc3d0a1a
Successfully tagged gwas:latest
registry
Using default tag: latest
The push refers to repository [localhost:5000/gwas]
Get http://localhost:5000/v2/: EOF
make: *** [Makefile:4: gwas.sif] Error 1
```

Running it one more time always solves the problem.
I haven't investigated what's the problem here...

**Comment by espenhgn** [comment]
Also saw this. No explanation (as of now).

**Comment by espenhgn** [comment]
Could this be due to sudo timeout? I also saw this when the Dockerfile build took a long time; on 2nd run, everything is buffered and fast. The timeout can be increased: https://unix.stackexchange.com/questions/382060/change-default-sudo-password-timeout

**Comment by espenhgn** [comment]
Closing, most likely a problem with our devbox, not the builds etc.
