### ISSUE TITLE
Move MAGMA and LAVA into its own github repository

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#54]
MAGMA software is released as binary, but it require a fairly large reference data, and for this reason it's best to move into  a separate github repository. 
LAVA tool is quite difference - it's is based on R, and it addresses a different question than MAGMA.
But it needs some of the reference files as MAGMA. Also, LAVA is developed by the same group as MAGMA. So it's reasonable to include LAVA in the same github repository - but perhaps in a separate .sif file (can be magma.sif and lava.sif).
The github repo can be https://github.com/comorment/magma

**Comment by espenhgn** [comment]
Is `lava-partitioning` (https://github.com/ofrei/lava-partitioning) depending on the same reference files? Does it make sense to include this via #51?
