### ISSUE TITLE
Move matlab-related software to separate github repo

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#55]
I don't think we fully established a container with MATLAB runtime to package software written in MATLAB.
Bayram have done a lot of work on this:
* https://github.com/comorment/gwas/tree/main/containers/matlabruntime - docker files to build container with MATLAB runtime 
* https://github.com/comorment/containers/tree/main/matlab - pre-built binaries with pleioFDR software (https://github.com/precimed/pleiofdr/)
* https://github.com/comorment/containers/tree/main/reference/pleiofdr - reference data from pleiOFDR analysis

Note that ``matlabruntime.sif`` as well as pre-build ``pleiofdr`` and ``magicsquare`` binaries can be build with a separate dev box. It's also hosted on NREC, but it's separate from the devbox where we build the rest of containers. This is because matlab runtime environment was pretty tricky to configure and make it compatible with docker / singularity.

I suggest to move all of this to a separate github repo, which already exists:
* https://github.com/comorment/matlabruntime 
Docs in this repo can be moved into ``src`` folder to be a bit more hidden, and we'll need a cleaner user docs for those users who want to run MATLAB code via container.

Later we can consider including other tools such as https://github.com/precimed/mostest/ and FEMA ( https://github.com/cmig-research-group/cmig_tools ) into MATLAB container.  However I consider this to be low priority, because MATLAB is somewhat too tricky to squeeze into a container. Perhaps it's best if users just stick to run MATLAB code in their own environment. 

So let's move everything matlab-related away from  github.com/comorment/containers repo, include it in https://github.com/comorment/matlabruntime  , and than put it all on hold and discuss whether or not we want to put more effort in MATLAB-related containers.

**Comment by espenhgn** [comment]
Sounds reasonable. I can remove the matlab stuff from #51
