### ISSUE TITLE
Move ipsychcnv.sif and enigma-cnv.sif into separate github repository

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#58]
I suggest moving development of ``ipsychcnv.sif`` and ``enigma-cnv.sif`` into a separate github repository, e.g. http://github.com/comorment/cnv , which should also include docker files, scripts, and other documentation related to these containers.  @bayramakdeniz does this sound reasonable?

**Comment by ofrei** [comment]
I realise there is already a repository [here](https://github.com/bayramakdeniz/iPsychCNV) , so it would be reasonable to include these two ``.sif`` files there. 
@bayramakdeniz could you transfer that repository from https://github.com/bayramakdeniz to https://github.com/comorment ? You can do this from project settings (https://github.com/bayramakdeniz/iPsychCNV/settings).
Please don't get me wrong - I don't mind at all that this repository is on your account and not under CoMorMent . That's totally fine. But that issue is that on your account we can't use a lot of GitLFS quota, i.e. hard to submit large .sif files. That's the only reason why I'm asking to move it here.

**Comment by bayramakdeniz** [comment]
For sure it is OK on my end to move but this repo to comorment is quite outdated. There is an active repo for enigmacnv.sif here: https://github.com/ENIGMA-git/ENIGMA-CNV/tree/main/CNVCalling/containers

Do you think we should also move this repo to comorment? I am not the sole owner of this repo

**Comment by ofrei** [comment]
@bayramakdeniz ENIGMA-git/ENIGMA-CNV repo can stay where it is, however I still think it's a good idea to transfer the older one ( https://github.com/bayramakdeniz/iPsychCNV ) to https://github.com/comorment. Please do that :)

**Comment by bayramakdeniz** [comment]
Done:)
https://github.com/comorment/iPsychCNV

**Comment by ofrei** [comment]
@bayramakdeniz sorry, it's not done - the .sif files are still located in github.com/comorment/containers . I'll fix that later today.
