### ISSUE TITLE
mixer.sif: image format not recognized

### ISSUE THREAD

**Issue by chenyangjjj** [comorment/containers#62]
Dear developers,

I am running the codes from mixer_simu.md file. The platform that I use is Centos_arm64 parallel in Macos M1 pro.
When I run the "singularity shell --home $PWD:/home $SIF/mixer.sif", it reports  "image format not recognized".
So is this due to the different architecture or other reasons?

**Comment by ofrei** [comment]
Hi,
thanks for reporting this. At the moment ARM architecture is not supported by mixer.sif container, it's built only for  x86. A reason for this is that mixer isn't going to run on a laptop, it require a larger HPC facility to complete analysis in a reasonable time.

**Comment by espenhgn** [comment]
Hi @chenyangjjj. There's a recent build of the `mixer.sif` container available at https://github.com/comorment/mixer (https://github.com/comorment/mixer/raw/main/singularity/mixer.sif). I don't know if much changed in this one, but perhaps you can test it? `singularity shell mixer.sif` works on my end (Saga cluster in Norway), singularity version 3.8.7-1.el7.

**Comment by chenyangjjj** [comment]
> Hi @chenyangjjj. There's a recent build of the `mixer.sif` container available at https://github.com/comorment/mixer (https://github.com/comorment/mixer/raw/main/singularity/mixer.sif). I don't know if much changed in this one, but perhaps you can test it? `singularity shell mixer.sif` works on my end (Saga cluster in Norway), singularity version 3.8.7-1.el7.
> 
> Btw., "image format not recognized" is explained by the fact that you only fetched the git LFS file reference, not the LFS file itself. Please have a look at https://git-lfs.github.com, and instructions on how to pull LFS files (`git lfs pull` or similar)

Hi, Thanks! The new mixer file works, although I don't know why. I guess it is due to the git? I am not sure. Thanks again anyway

**Comment by espenhgn** [comment]
> > Hi @chenyangjjj. There's a recent build of the `mixer.sif` container available at https://github.com/comorment/mixer (https://github.com/comorment/mixer/raw/main/singularity/mixer.sif). I don't know if much changed in this one, but perhaps you can test it? `singularity shell mixer.sif` works on my end (Saga cluster in Norway), singularity version 3.8.7-1.el7.
> > Btw., "image format not recognized" is explained by the fact that you only fetched the git LFS file reference, not the LFS file itself. Please have a look at https://git-lfs.github.com, and instructions on how to pull LFS files (`git lfs pull` or similar)
> 
> Hi, Thanks! The new mixer file works, although I don't know why. I guess it is due to the git? I am not sure. Thanks again anyway

Sounds good! I think git LFS is the most likely culprit. We *should* not provide large binary files in git repositories directly, hence they here exist as small reference files pointing to the actual file itself, but this introduces some additional hurdles :)

I'm closing this then as resolved.
