### ISSUE TITLE
meta-analysis with METAL or GWAMA 

### ISSUE THREAD

**Issue by ofrei** [comorment/containers#7]
We need one (or both) of these tools in a container:
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-288
https://genome.sph.umich.edu/wiki/METAL_Documentation

**Comment by joellepasman** [comment]
Maybe also check out rareGWAMA, https://github.com/dajiangliu/rareGWAMA

**Comment by joejeroe** [comment]
Maybe we want to extend this issue to maybe have a list of multiple options? It might be that both methods are suboptimal compared to a more recent method.

**Comment by ofrei** [comment]
* GWAMA was added to  gwas.sif , with demo data included, and brief usage example here: https://github.com/comorment/containers/blob/main/usecases/meta_simu.md
* rareGWAMA was added to  r.sif container , based on r 4.0.3. I haven't tried using this - please let me know if it doesn't work.
* METAL had already been available in gwas.sif 

For the reference, here is the change in container definitions where this was implemented: https://github.com/comorment/gwas/commit/e93b6c112ddac9c13cdbe554109e8796bf701ecc

**Comment by ofrei** [comment]
@joejeroe to your question, I think for now we could use directly the original tools (MAGMA  / GWAMA), and then see if we need for higher level scripts (like gwas.py) to organize meta-analysis workflows. If we go for it - yes, great to support multiple options, but for now I think using MAGMA / GWAMA directly is good enough

**Comment by ofrei** [comment]
I'll close the ticket, feel free to reopen if some of the tools aren't working / if there is anything else to add
