### ISSUE TITLE
tool requests

### ISSUE THREAD

**Issue by joellepasman** [comorment/containers#8]
Tools that could be added to the containers:
- MAGMA https://ctg.cncr.nl/software/magma 
- Rpackage Genomic SEM https://github.com/GenomicSEM/GenomicSEM
- Rpackage Two Sample Mendelian Randomization https://mrcieu.github.io/TwoSampleMR/
- Rpackage gsmr
(+ dependencies and secondary tools)

**Comment by joellepasman** [comment]
Also, maybe we should discuss if we want to use PRSice for all our PRS work. For example, we could implement LDpred, GCTA-SBLIP or SBayesR, which have shown greater power and accuracy.

**Comment by ofrei** [comment]
@joellepasman Noted, I'll look into this - thank you!
 
For PRS computation, I think we can start with PRSice2 because it's basic and very simple, but indeed it's good to have other software on your list available. Could you please include the download links or documentation for ``LDpred``, ``GCTA-SBLIP`` and ``SBayesR`` tools? I'm aware of these tools, just want to double-check (e.g. SBayesR is probably part of the GCTB package which I'm partly confusing with GCTA ).

**Comment by joellepasman** [comment]
GSMR: https://cnsgenomics.com/software/gsmr/
LDpred: https://github.com/bvilhjal/ldpred 
GCTA-SBLUP: https://cnsgenomics.com/software/gcta/#SBLUP
SBayesR: https://cnsgenomics.com/software/gctb/#Tutorial

**Comment by ofrei** [comment]
* MAGMA was added to gwas.sif
* GenomicSEM, TwoSampleMR, and GSMR tools were added to r.sif
* LDpred was added to python3.sif
* GCTA-SBLUP and SBayesR are part of GCTA and GCBT tools which are already available  in gwas.sif. 
* prsice2 is already part of gwas.sif

For the MAGMA, I've included the official MAGMA reference data in $COMORMENT/containers/reference/magma. Then one should simply follow official MAGMA tutorial, https://ctg.cncr.nl/software/magma . 

For  GCTA and GCTB  I wasn't sure what test data should be included - please let me know if there are some demo datasets needed to follow https://cnsgenomics.com/software/gctb/#Tutorial or  https://cnsgenomics.com/software/gcta/#SBLUP, it would be good to include those dataset in https://github.com/comorment/containers/tree/main/reference/examples 

I haven't tested GenoicSEM and TwoSampleMR packages - please let me know if you have a chance to try the out and they don't work.

For GSMR, the demo data is available in $COMORMENT/containers/reference/example/gsmr , and one could follow https://cnsgenomics.com/software/gsmr/ tutorial  (see some notes [here](https://github.com/comorment/containers/blob/main/docs/r.md) ).

For LD pred, I've tested that its unit tests work well (``ldpred-inttest``) and ``ldpred --help`` works, but I haven't made a use case.

Close for now, please reopen if any of the tools have problems

**Comment by joellepasman** [comment]
Here are the tutorial data for GCTB (I don't think there is a tutorial for SBLUP): https://cnsgenomics.com/software/gctb/#Download 

Some additional tools that would be good to include (I definitely want to use HDL):

Latent causal variable model: https://github.com/lukejoconnor/LCV 
High-Definition Likelihood for genetic correlation: https://github.com/zhenin/HDL
S-PrediXcan: https://github.com/hakyimlab/MetaXcan

We might also want to use within-family MR but I think that's not a separate package or if there's even an established way of doing it, do you have thoughts about that?
