### ISSUE TITLE
`gwas.sif`: `metal` software license?

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#85]
The copyright statement of `metal` source codes is a bit restrictive: 
```
////////////////////////////////////////////////////////////////////// 
// metal/Main.h 
// (c) 2000-2011 Goncalo Abecasis
// 
// This file is distributed as part of the Goncalo source code package   
// and may not be redistributed in any form, without prior written    
// permission from the author. Permission is granted for you to       
// modify this file for your own personal use, but modified versions  
// must retain this copyright notice and must not be distributed.     
// 
// Permission is granted for you to use this file to compile Goncalo.    
// 
// All computer programs have bugs. Use this file at your own risk.   
// 
// Friday March 25, 2011
// 
```
while the precompiled binary distribution does not carry a proper license statement/file except for the Mersenne Twister RNG used by this software. 
Should we keep it? It has not been maintained since 2011.

**Comment by ofrei** [comment]
@espenhgn good point. Let's ask the author, and see if we can redistribute this tool while (while of course keeping the reference to original software page and asking to cite the publication).

**Comment by espenhgn** [comment]
Closing, we got explicit permission from the author of this tool to include the binary in our builds.
