### ISSUE TITLE
Manhattan plot (python_convert)

### ISSUE THREAD

**Issue by joellepasman** [comorment/containers#9]
For some reason the Mahattan plot utility from python_convert only includes about 45,000 of the ~8 mil SNPs in my summary statistics, without outputting any warnings or errors. What reference data is used?

It would be great if more information can be added about the usage of the clump utility (sumstats.py). What are the minimum required flags? What are the defaults? What is the reference dataset? To unify these processes across different sites as much as possible we probably should pre-set as many of the parameters as we can.

**Comment by joellepasman** [comment]
This command:
$PYTHON /tools/python_convert/sumstats.py clump \
--sumstats sumstats.gz \
--out hitsfile \
--force

**Comment by ofrei** [comment]
@joellepasman here is an example for ``sumstats.py clump``:
https://github.com/precimed/python_convert#sumstatspy-clump
as ``--bfile-chr`` you may use the data from here https://github.com/comorment/reference/tree/main/1000genomes 
But I also consider re-running basic QC of 1kG phase3 data, after carefully documenting all  QC steps, and including the result in https://github.com/comorment/containers/tree/main/reference folder.

>python_convert only includes about 45,000 of the ~8 mil SNPs 

That's not ok, could you please copy here the log file (output of the sumstats.py call) showing more details?

**Comment by joellepasman** [comment]
I think the clump utility needs some streamlining. E.g., I don't have an own plink version installed, because I only use the containerized one. Calling it with singularity within the clump command doesn't work. Fortunately, it runs without specifying the plink program. The only option that does not work anymore is exclude-range, but that can be solved by adding a step to remove it afterwards or simply remove a range from the sumstats (to make sure this step is also harmonised across the cohorts). So fyi, this works:

```
$PYTHON /tools/python_convert/sumstats.py clump \
--force \
--sumstats file \
--clump-p1 1e-05 \
--bfile-chr $COMORMENT/containers/reference/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@ \
--out hits
```

Below is the full output of th Manhattan plot command. I already tried it with a different filename (to address the error message) but that didn't matter. I also tried it on a different dataset, results were the same. Weird, right? This utility does not use sumstats for mapping, does it? Because in that case it could be a compatibility issue. 

```
Filtering _MDD.regenie
8891524 SNPs in _MDD.regenie
8891524 SNPs with non-null SNP
8891524 SNPs with defined p-value
8891524 SNPs within specified chromosomes
8891524 SNPs with non-zero p-value
Preparing SNPs for plotting
0 outlined SNPs
0 bold SNPs
0 annotated SNPs
44457 SNPs will be plotted in total
Making plot
MDD/iCBT/MDD.manh.png was generated
/tools/python_convert/manhattan.py:199: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series([])
/tools/python_convert/manhattan.py:498: UserWarning: The handle <matplotlib.patches.Patch object at 0x2b3a6ef83490> has a label of '_MDD' which cannot be automatically added to the legend.
  ax.legend(handles=handles, loc=args.legend_location)
```

**Comment by ofrei** [comment]
@joellepasman For the "sumstats.py clump" procedure,  you are doing it correctly - it's OK not to provide plink, then it'll use the plink from container. The --exclude-range option is a very poorly named one  (and also incorrectly documented). The implementation of this flag is not supposed to exclude the range, but it will make sure that no more than 1 loci is reported in that range. I think this makes more sense than removing such a loci like MHC. If you really want to remove a loci, then you could rung "sumstats.py qc --exclude-range" on your summary stats prior to calling "sumstats.py clump".

As for manhatatn plot, once again this is non-intuitive behaviour. To plot all SNPs please add "--downsample-frac  1.0" argument. The idea here was to only plot --downsample-frac fraction of SNPs (by default 0.005), but keep all SNPs above certain threshold (e.g. genome-wide significant). This is helpful when one creates .svg files which tend to be very large if all SNPs are represented on a figure. Here is the line in the code which does the trick: https://github.com/precimed/python_convert/blob/master/manhattan.py#L278 .

So it seem that both issues here are actually "by design" - but very poorly documented / non-intuitively named. Please keep this ticket open and I'll address this.

**Comment by joellepasman** [comment]
If you get to this, please note that the Manhattan plot command works correctly now. It creates 6 files, and the ones with the extensions `.png.* `work fine. However, there's 2 files that are huge (`.pdf` is 108 Mb and `.svg` is 750 Mb) and I cannot seem to open them (Adobe Illustrator and Acrobat crashed on me). You might want to delete the commands that create these files. As for the details, you could consider touching up the appearance a bit or building in some formatting functionality. 

Also, the clump command works fine, only the --exclude-range(s) option you provide as an example is not recognized. I've tried some variations on your example `--exclude-ranges ['6:25119106-33854733', '8:7200000-12500000'] \`, but it keeps throwing the error message `ValueError: Unable to interpret exclude range "[6:25119106-33854733,", chr:from-to format is expected.`

No hurry, just some extra things to consider if you start working on these issues!

**Comment by ofrei** [comment]
@joellepasman thank you. For the ``--exclude-ranges``, the correct syntax is as follows:
```
--exclude-ranges 6:25119106-33854733 8:7200000-12500000
```
Please let me know if this works. I should fix the example and remove symbols all of the ``[``, ``'`` and ``,``  symbols that are really misleading. Could you point me to a place which contained this wrong syntax?

For the size of the .pdf and .svg files, this is exactly the reason to why  --downsample-frac option was implemented. If you plot all points (i.e. 10+ million), then .pdf and .svg will be huge and non-usable. These forward store graphics in a vector format, but there is really no need to draw every single point for p values that doesn't reach significance. The .png format doesn't have this problem as it non-vector graphics format, but then you can't edit or rescale the figure the way it works for .svg. 

I'm happy to improve python_convert to make it more usable, let's discuss at the next meeting what needs to be done before I start making changes.
